# Generated by Django 2.0.6 on 2018-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("name", "id",),
            },
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('ip_address', 'port')},
        ),
    ]
